---
title: "R Notebook"
output: html_notebook
---

# Importando bibliotecas

```{r}
library(bnlearn)
library(igraph)
library(dplyr)
library(gplots)
library(Rgraphviz)
library(dplyr)
library(ROSE)
```

```{r}

setwd("C:\\Users\\Pichau\\INMET")

df_reduzido_discretas = read.csv("C:/Users/Pichau/INMET/TODAS_ESTACOES/df_reduzido_discretas_renomeado.csv", header = TRUE, sep = ",")

df_reduzido_discretas[] <- lapply(df_reduzido_discretas, as.factor)

```

```{r}


df_reduzido_discretas <- df_reduzido_discretas %>%
  rename(
    # Radiation
    R_1h = radiacao_valor1,
    R_2h = radiacao_valor2,
    R_3h = radiacao_valor3,

    # Humidity
    H_1h = umid_valor1, 
    H_2h = umid_valor2, 
    H_3h = umid_valor3,

    # Temperature
    T_1h = temp_valor1,
    T_2h = temp_valor2,
    T_3h = temp_valor3,

    # Pressure
    P_1h = pressao_valor1,
    P_2h = pressao_valor2,
    P_3h = pressao_valor3,

    # Dew Point Temperature
    DT_1h = orvalho_valor1,
    DT_2h = orvalho_valor2,
    DT_3h = orvalho_valor3,

    # Wind Speed
    W_1h = vento_valor1,
    W_2h = vento_valor2,
    W_3h = vento_valor3,

    # Rain
    Rain = chuva,

    # Season
    S = estacao_ano,

    # Shift / Time of day
    Day_p = turno
  )

df_reduzido_discretas[] <- lapply(df_reduzido_discretas, as.factor)

source("C:\\Users\\Pichau\\INMET\\funcao_blacklist\\blacklist_siglas.R")


```

# Estrutura da Rede Bayesiana Hc bic
```{r}
rb_BIC <- hc(df_reduzido_discretas, blacklist = bl, score = "bic")
rb_BIC
```

# BOOTSTRAP, 300 vezes para calcular a estrutura da rede média HC bic. 

```{r}

str.diff_bic = boot.strength(df_reduzido_discretas, R = 300, algorithm = "hc",
                             algorithm.args = list(blacklist = bl, score = "bic"))

```


```{r}
avg.simpler = averaged.network(str.diff_bic, threshold = 0.85)

avg.simpler
```
# Gerou undirected arcs:   


```{r}
avg.simpler <- bnlearn::drop.arc(avg.simpler, from = "R_3h", to = "P_3h")
avg.simpler <- bnlearn::drop.arc(avg.simpler, from = "P_3h", to = "R_3h")
avg.simpler
```


```{r}
no_alvo <- which(V(g)$name == "T_3H")  # encontra índice do nó

layout_sugi[no_alvo, ] <- c(500, 125)
```




```{r}
library(igraph)

g <- as.igraph(avg.simpler)

layout_sugi <- layout_with_sugiyama(g)$layout

# Ajustar espaçamento
layout_sugi[,2] <- layout_sugi[,2] * 15 # aumenta distância vertical
layout_sugi[,1] <- layout_sugi[,1] * 20.5  # aumenta distância horizontal


no_alvo <- which(V(g)$name == "R_2h")  # encontra índice do nó

layout_sugi[no_alvo, ] <- c(540, 135)      # define nova posição

no_alvo <- which(V(g)$name == "T_3h")  # encontra índice do nó

layout_sugi[no_alvo, ] <- c(330, 125)



png("C:/Users/Pichau/INMET/Estruturas das Redes Bayesianas/REDE_FINAL/estrutura_final_HC_BIC_abreviada.png", 
    width = 6440, height = 6160, res = 300  )

plot(
  g,
  layout = layout_sugi,
  vertex.label = V(g)$name,
  vertex.label.cex = 2.20,
  vertex.label.font = 2 ,  
  vertex.label.color = "black",
  vertex.label.dist = 0,
  vertex.size = 25,
  vertex.color = "lightblue",
  vertex.shape = "rectangle",
  edge.arrow.size = 0.4,
  edge.color = "black",
  margin = -0.11,
  vertex.frame.color = "black",
  vertex.label.dist = 0.5
)

dev.off()


```


# testando novos tamanhos



```{r}
g <- as.igraph(avg.simpler)

layout_sugi <- layout_with_sugiyama(g)$layout


png("C:/Users/Pichau/INMET/Estruturas das Redes Bayesianas/REDE_FINAL/estrutura_final_HC_BIC_abreviada_testando.png", 
   width = 6440, height = 6160, res = 950  )

# Plotar com melhorias visuais
plot(
  g,
  layout = layout_sugi,
  vertex.label = V(g)$name,
  vertex.size = 14,
  vertex.label.cex = 0.4,
  vertex.label.color = "black",
  vertex.color = "lightblue",
  vertex.shape = "rectangle",
  edge.arrow.size = 0.2,
  edge.color = "gray40",
  margin = 0.05,

)

dev.off()
```

```{r}
g <- as.igraph(avg.simpler)

layout_sugi <- layout_with_sugiyama(g)$layout


png("C:/Users/Pichau/INMET/Estruturas das Redes Bayesianas/REDE_FINAL/estrutura_final_HC_BIC_abreviada_testando.png", 
   width = 2480, height = 3508, res = 950  )

# Plotar com melhorias visuais
plot(
  g,
  layout = layout_sugi,
  vertex.label = V(g)$name,
  vertex.size = 14,
  vertex.label.cex = 0.4,
  vertex.label.color = "black",
  vertex.color = "lightblue",
  vertex.shape = "rectangle",
  edge.arrow.size = 0.2,
  edge.color = "gray40",
  margin = 0.05,

)

dev.off()
```